package cn.warriorview.animation.engine;

import com.github.retrooper.packetevents.PacketEvents;
import com.github.retrooper.packetevents.wrapper.PacketWrapper;
import com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerBundle;

import it.unimi.dsi.fastutil.objects.ObjectArrayList;

import org.bukkit.entity.Player;

import java.util.IdentityHashMap;
import java.util.Map;

// ─── Bundle-delimiter protocol (MC 1.19.4+) ─────────────────────────────────
// The client treats all packets between two BUNDLE_DELIMITER packets as a
// single atomic 'bundle', applying them together in one client game-tick step.
// WrapperPlayServerBundle() (no-args) IS the delimiter packet itself — so a
// flush looks like: [DELIMITER] → packet₀ → packet₁ → … → [DELIMITER].
// This means N animations on screen still cost exactly 1 Netty channel write
// per player instead of one write per packet. ─────────────────────────────────

/**
 * Per-tick packet accumulator: implements the "private mailbox + bundle merge" pattern.
 *
 * <h3>How it works</h3>
 * <ol>
 *   <li>For each packet generated by any animation in a tick, call
 *       {@link #collect(Player[], int, PacketWrapper)} — the same wrapper object is
 *       stored by pointer in every viewer's mailbox (flyweight, 0 copies).</li>
 *   <li>At the end of the tick call {@link #flush()} — each player receives exactly
 *       <em>one</em> {@link WrapperPlayServerBundle} containing all packets destined
 *       for them, regardless of how many concurrent animations contributed packets.</li>
 * </ol>
 *
 * <h3>Memory</h3>
 * The {@link IdentityHashMap} and each per-player {@link ObjectArrayList} are reused
 * across ticks; only the list cursors are reset in {@link #flush}, so no GC pressure
 * from repeated allocation.  Call {@link #remove(Player)} on player quit to release
 * the stale map entry.
 *
 * <p>Not thread-safe; must be driven from a single engine thread.</p>
 */
public final class PacketCollector {

    /** Per-player outbox. IdentityHashMap avoids Player.hashCode() / equals() overhead. */
    private final IdentityHashMap<Player, ObjectArrayList<PacketWrapper<?>>> mailboxes =
            new IdentityHashMap<>();

    /**
     * Shared stateless delimiter sentinel; allocated once for the lifetime of the JVM.
     * Safe to reuse: WrapperPlayServerBundle carries no mutable per-send state.
     */
    private static final WrapperPlayServerBundle DELIMITER = new WrapperPlayServerBundle();

    // ── Collection ────────────────────────────────────────────────────────────

    /**
     * Appends {@code packet} to every viewer's mailbox.
     *
     * <p>Only a <em>pointer</em> is stored — the packet object must be treated as
     * immutable after this call (it will be shared across all viewer mailboxes).</p>
     *
     * @param viewers player array, may be over-sized
     * @param count   number of valid entries at the start of {@code viewers}
     * @param packet  immutable packet wrapper to deliver
     */
    public void collect(Player[] viewers, int count, PacketWrapper<?> packet) {
        for (int i = 0; i < count; i++) {
            Player p = viewers[i];
            ObjectArrayList<PacketWrapper<?>> box = mailboxes.get(p);
            if (box == null) {
                box = new ObjectArrayList<>(8);
                mailboxes.put(p, box);
            }
            box.add(packet); // pointer copy only — flyweight
        }
    }

    // ── Flush ─────────────────────────────────────────────────────────────────

    /**
     * Sends all accumulated packets to their respective players, then clears
     * all mailboxes for the next tick.
     *
     * <ul>
     *   <li>1 packet → sent directly (no Bundle overhead).</li>
     *   <li>≥2 packets → wrapped between two
     *       {@link WrapperPlayServerBundle BUNDLE_DELIMITER} sentinel packets so the
     *       client processes them atomically in a single game-tick step.</li>
     * </ul>
     *
     * Players that disconnected during the tick are silently skipped.
     */
    public void flush() {
        for (Map.Entry<Player, ObjectArrayList<PacketWrapper<?>>> entry : mailboxes.entrySet()) {
            ObjectArrayList<PacketWrapper<?>> box = entry.getValue();
            if (box.isEmpty()) continue;

            var user = PacketEvents.getAPI().getPlayerManager().getUser(entry.getKey());
            if (user == null) {
                box.clear();
                continue;
            }

            if (box.size() == 1) {
                user.sendPacket(box.get(0));
            } else {
                user.sendPacket(DELIMITER);                   // open
                for (int i = 0; i < box.size(); i++) {
                    user.sendPacket(box.get(i));
                }
                user.sendPacket(DELIMITER);                   // close
            }

            box.clear(); // 0-GC: reuse the ObjectArrayList allocation next tick
        }
    }

    // ── Lifecycle ─────────────────────────────────────────────────────────────

    /**
     * Removes the player's mailbox entry entirely.
     * Call this when a player quits to prevent the IdentityHashMap from retaining
     * a stale {@link Player} reference.
     */
    public void remove(Player player) {
        mailboxes.remove(player);
    }
}
