package cn.warriorview.animation.engine;

import com.github.retrooper.packetevents.PacketEvents;
import com.github.retrooper.packetevents.manager.player.PlayerManager;
import com.github.retrooper.packetevents.protocol.player.User;
import com.github.retrooper.packetevents.wrapper.PacketWrapper;
import com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerBundle;

import io.netty.channel.Channel;
import io.netty.channel.EventLoop;

import it.unimi.dsi.fastutil.objects.ObjectArrayList;

import org.bukkit.entity.Player;

import java.util.IdentityHashMap;

// ─── Bundle-delimiter protocol (MC 1.19.4+) ─────────────────────────────────
// The client treats all packets between two BUNDLE_DELIMITER packets as a
// single atomic 'bundle', applying them together in one client game-tick step.
// WrapperPlayServerBundle() (no-args) IS the delimiter packet itself — so a
// flush looks like: [DELIMITER] → packet₀ → packet₁ → … → [DELIMITER].
// This means N animations on screen still cost exactly 1 Netty channel write
// per player instead of one write per packet. ─────────────────────────────────

/**
 * Per-tick packet accumulator: implements the "private mailbox + bundle merge" pattern.
 *
 * <h3>How it works</h3>
 * <ol>
 *   <li>For each packet generated by any animation in a tick, call
 *       {@link #collect(Player[], int, PacketWrapper)} — the same wrapper object is
 *       stored by pointer in every viewer's mailbox (flyweight, 0 copies).</li>
 *   <li>At the end of the tick call {@link #flush()} — each player receives exactly
 *       <em>one</em> {@link WrapperPlayServerBundle} containing all packets destined
 *       for them, regardless of how many concurrent animations contributed packets.</li>
 * </ol>
 *
 * <h3>Memory</h3>
 * The {@link IdentityHashMap} and each per-player {@link ObjectArrayList} are reused
 * across ticks; only the list cursors are reset in {@link #flush}, so no GC pressure
 * from repeated allocation.  Call {@link #remove(Player)} on player quit to release
 * the stale map entry.
 *
 * <h3>Single-EventLoop-task optimization</h3>
 * For each player, {@link #flush()} submits exactly <b>one</b> task to the player's
 * Netty {@link EventLoop} that performs all writes + a single flush inline.
 * From non-EventLoop threads, every {@code channel.write/flush} call submits an
 * additional task; wrapping the whole batch in {@code eventLoop.execute()} reduces
 * N+1 task submissions to <b>1</b> and N TCP pushes to <b>1</b>.
 *
 * <p>Not thread-safe; must be driven from a single engine thread.</p>
 */
public final class PacketCollector {

    /** Per-player outbox. IdentityHashMap avoids Player.hashCode() / equals() overhead. */
    private final IdentityHashMap<Player, ObjectArrayList<PacketWrapper<?>>> mailboxes =
            new IdentityHashMap<>();

    /**
     * Cached PacketEvents {@link User} objects keyed by {@link Player} identity.
     * Populated lazily on first {@link #collect} and invalidated in {@link #remove}.
     */
    private final IdentityHashMap<Player, User> userCache = new IdentityHashMap<>();

    /**
     * Cached Netty {@link EventLoop} per player — derived from the player's Channel
     * on first use, stays stable for the connection lifetime.
     * Cached here to avoid repeated {@code (Channel) user.getChannel().eventLoop()} calls.
     */
    private final IdentityHashMap<Player, EventLoop> eventLoopCache = new IdentityHashMap<>();

    /**
     * Players who received at least one packet this tick.
     * Maintained by {@link #collect} so {@link #flush} iterates only active viewers
     * instead of scanning all historic mailbox entries.
     */
    private final ObjectArrayList<Player> dirtyPlayers = new ObjectArrayList<>(64);

    /**
     * Shared stateless delimiter sentinel; allocated once for the lifetime of the JVM.
     * Safe to reuse: WrapperPlayServerBundle carries no mutable per-send state.
     */
    private static final WrapperPlayServerBundle DELIMITER = new WrapperPlayServerBundle();

    // ── Collection ────────────────────────────────────────────────────────────

    /**
     * Appends {@code packet} to every viewer's mailbox.
     *
     * <p>Only a <em>pointer</em> is stored — the packet object must be treated as
     * immutable after this call (it will be shared across all viewer mailboxes).</p>
     *
     * @param viewers player array, may be over-sized
     * @param count   number of valid entries at the start of {@code viewers}
     * @param packet  immutable packet wrapper to deliver
     */
    public void collect(Player[] viewers, int count, PacketWrapper<?> packet) {
        for (int i = 0; i < count; i++) {
            Player p = viewers[i];
            ObjectArrayList<PacketWrapper<?>> box = mailboxes.get(p);
            if (box == null) {
                box = new ObjectArrayList<>(8);
                mailboxes.put(p, box);
            }
            if (box.isEmpty()) {
                dirtyPlayers.add(p); // mark as active this tick (first packet for this player)
            }
            box.add(packet); // pointer copy only — flyweight
        }
    }

    // ── Flush ─────────────────────────────────────────────────────────────────

    /**
     * Sends all accumulated packets to their respective players, then clears
     * all mailboxes for the next tick.
     *
     * <ul>
     *   <li>1 packet → sent directly (no Bundle overhead).</li>
     *   <li>≥2 packets → wrapped between two
     *       {@link WrapperPlayServerBundle BUNDLE_DELIMITER} sentinel packets so the
     *       client processes them atomically in a single game-tick step.</li>
     * </ul>
     *
     * Players that disconnected during the tick are silently skipped.
     */
    public void flush() {
        if (dirtyPlayers.isEmpty()) return;

        PlayerManager pm = PacketEvents.getAPI().getPlayerManager();
        for (int d = 0; d < dirtyPlayers.size(); d++) {
            Player p = dirtyPlayers.get(d);
            ObjectArrayList<PacketWrapper<?>> box = mailboxes.get(p);

            User user = userCache.get(p);
            if (user == null) {
                user = pm.getUser(p);
                if (user == null) {
                    box.clear();
                    continue;
                }
                userCache.put(p, user);
            }

            EventLoop el = eventLoopCache.get(p);
            if (el == null) {
                el = ((Channel) user.getChannel()).eventLoop();
                eventLoopCache.put(p, el);
            }

            // Swap out the full box so collect() can immediately start filling a
            // fresh one for the next tick without waiting for the EventLoop task.
            final ObjectArrayList<PacketWrapper<?>> toSend = box;
            mailboxes.put(p, new ObjectArrayList<>(8));

            // Submit ONE task to the player's EventLoop.
            // Inside the EventLoop thread, channel.write/flush execute synchronously
            // (no further task submissions), so the entire bundle is 1 task + 1 flush.
            final User finalUser = user;
            el.execute(() -> {
                if (toSend.size() == 1) {
                    finalUser.sendPacket(toSend.get(0));
                } else {
                    finalUser.writePacket(DELIMITER);
                    for (int i = 0; i < toSend.size(); i++) finalUser.writePacket(toSend.get(i));
                    finalUser.writePacket(DELIMITER);
                    finalUser.flushPackets();
                }
                // toSend is unreferenced after this; eligible for GC.
            });
        }
        dirtyPlayers.clear();
    }

    // ── Lifecycle ─────────────────────────────────────────────────────────────

    /**
     * Removes the player's mailbox entry entirely.
     * Call this when a player quits to prevent the IdentityHashMap from retaining
     * a stale {@link Player} reference.
     */
    public void remove(Player player) {
        mailboxes.remove(player);
        userCache.remove(player);
        eventLoopCache.remove(player);
    }
}
